<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HPRED extends Model
{
    protected $table = 'HPRED';

    protected $fillable = [
        'NOPRESTACION',
        'NOITEM',
        'IDSERVICIO',
        'CANTIDAD',
        'VALOR',
        'VALORCOPAGO',
        'VALOREXCEDENTE',
        'IDPLAN',
        'IMPRESO',
        'AUTORIZADO',
        'COMENTARIOS',
        'IDPROVEEDOR',
        'IDCONCEPTORIPS',
        'AMBITO',
        'FINALIDAD',
        'PERSONAL_AT',
        'DXPPAL',
        'DXRELACIONADO',
        'COMPLICACION',
        'FORMAQX',
        'VALORPCOMP',
        'USUARIO',
        'UTISOAT',
        'VLRFALTAAPLICARSOAT',
        'CONSECUTIVOCX',
        'ITEMCIRUGIA',
        'IDCIRUGIA',
        'TIPOSERCIRUGIA',
        'FACTURADA',
        'N_FACTURA',
        'VLRAPLICADO1',
        'VLRAPLICADO2',
        'CANTIDADORIGINAL',
        'CANTIDADDEVUELTA',
        'CNSIDEV',
        'INDDEVOLUCION',
        'INDDEVAPLICADA',
        'USUARIODEV',
        'NOCOBRABLE',
        'PCOSTO',
        'CXP',
        'FECHA',
        'VIA',
        'IDAREAH',
        'IDAREA',
        'NIVELATENCION',
        'PEDIDOINV',
        'NOLOTE',
        'COBRARA',
        'IDTERCEROCA',
        'PCUBRIMIENTO',
        'TIPODTO',
        'DESCUENTO',
        'NORDEN',
        'VALORTOTALCOSTO',
        'CCOSTO',
        'ENLAB',
        'CNSMOV',
        'NOAUTORIZACION',
        'AQUIENCOBRO',
        'DOSISAPL',
        'VLRAPLICADO3',
        'LABO_RESID',
        'HPREDID',
        'REGVLRMANUAL',
        'CONSECUTIVOCIT',
        'PROCREALIZADO',
        'PROCREALIZADOFECHA',
        'PROCINFREALIZADO',
        'PROCINFREALIZADOFECHA',
        'ESDEINV',
        'FACTURABLE',
        'NOPOS',
        'TIPOCONTRATO',
        'KNEGID',
        'IDTARIFA',
        'ITEM_TAR',
        'capitado',
        'ACCION',
        'KCNTRID',
        'IDCONCEPTODTO',
        'NOPRESTACIONREL',
        'NOITEMREL',
        'VALORREL',
        'IDSERVICIOREL',
        'PAQUETE',
        'SERRID',
        'TIPOTTEC',
        'TIPOSISTEMA',
        'KCNTID',
        'KCNTCAID',
        'IDT',
        'HADMEFID'
    ];

    public $timestamps = false;

    public function hpre() {
        return $this->belongsTo('App\HPRE', 'NOPRESTACION');
    }
}
